export const LOGGEDIN = 'LOGGEDIN';
export const BOOKMARKSTATE = 'BOOKMARKSTATE';
export const ADDALLITEMS = 'ADDALLITEMS';
export const ADDITEMTOBOOKMARK = 'ADDITEMTOBOOKMARK';
export const REMOVEFROMBOOKMARK = 'REMOVEFROMBOOKMARK';
export const LOGGEDOUT = 'LOGGEDOUT';
export const UPDATEALLITEMS ='UPDATEALLITEMS';